# Generated by Django 4.0 on 2024-10-12 03:04

import apps.django_printforms.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='template name')),
                ('code', models.CharField(blank=True, help_text='example: "content_templates/base.html"', max_length=100, null=True, unique=True, verbose_name='template code')),
                ('content', models.TextField(verbose_name='template text')),
                ('help_message', models.JSONField(blank=True, default=apps.django_printforms.models.help_message_default, help_text='variable dictionary example in json', null=True, verbose_name='dictionary example')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
